### ISSUE TITLE
'zhPopupController.h' file not found

### ISSUE THREAD

**Issue by afiq90** [snail-z/zhPopupController#18]
Hi there, 

I tried to use this great library in my old app, but I got an error **'zhPopupController.h' file not found**, anybody have an idea what cause this problem. thanks in advance.

**Comment by snail-z** [comment]
Whether to use cocoapods?

**Comment by afiq90** [comment]
Yes, I'm using cocoapod, plus I got this error :

>   "_OBJC_CLASS_$_zhPopupController", referenced from:
>    objc-class-ref in LoyaltyProgramHome.o
> ld: symbol(s) not found for architecture arm64
> clang: error: linker command failed with exit code 1 (use -v to see invocation)

**Comment by snail-z** [comment]
I want to know your compilation environment ? 
zhPopupController Requires iOS 7.0 or later and  Automatic Reference Counting (ARC)

**Comment by afiq90** [comment]
I'm using xcode 9, deployment target is 7.1 and yes i'm using ARC

**Comment by snail-z** [comment]
https://stackoverflow.com/questions/19213782/undefined-symbols-for-architecture-arm64
Is this article helpful to you?

**Comment by afiq90** [comment]
thank you, you're the best
