### ISSUE TITLE
有个bug

### ISSUE THREAD

**Issue by 392222523** [snail-z/zhPopupController#6]
连续弹出2个view就消失不了

**Comment by snail-z** [comment]
怎么会连续弹出两个view?能说下具体情况吗  或是你的使用场景是什么样的？

**Comment by 392222523** [comment]
在网络请求失败的时候弹窗,然后一个页面有2个请求,没网络状态会弹2个

**Comment by 392222523** [comment]
SnailAlertView *alert = [[SnailAlertView alloc] initWithTitle:title message:message fixedWidth:300];
    alert.linesHidden = YES;
    
    
    SnailAlertButton *can = [SnailAlertButton cancelButtonWithTitle:cancelTitle handler:cancel];
    
    can.edgeInset = UIEdgeInsetsMake(20, 20, 20, 20);
    can.backgroundColor = [UIColor whiteColor];
    [can.layer setBorderColor:[[UIColor blackColor] CGColor]];
    
    can.layer.borderWidth = 0.5;
    [can.layer masksToBounds];
    
    [can setTitleColor:[UIColor blackColor] forState:UIControlStateNormal];
    
    [alert addAction:can];
    
    
    AppDelegate *ad = (AppDelegate*)[UIApplication sharedApplication].delegate;
    ad.window.sl_popupController = [SnailPopupController new];

    ad.window.sl_popupController.maskType = PopupMaskTypeBlackBlur;
    ad.window.sl_popupController.transitStyle = PopupTransitStyleShrinkInOut;
    [ad.window.sl_popupController presentContentView:alert duration:0.5 elasticAnimated:YES];

**Comment by 392222523** [comment]
ad.window.sl_popupController = [SnailPopupController sl_popupController];
用这个初始化,会有个蒙版消失不了.检查视图发现还是2个view.dismiss不掉.

**Comment by 392222523** [comment]
- (void)buttonClicked:(UIButton *)sender {
    NSString *selName = [NSString stringWithFormat:@"example%lu", sender.tag + 1];
    SEL sel = NSSelectorFromString(selName);
    if ([self respondsToSelector:sel]) {
        self.title = _styles[sender.tag];
        [self performSelector:sel withObject:nil afterDelay:0];
        [self performSelector:sel withObject:nil afterDelay:0];  // 在demo中连续调用2次就会出现.


    }
}

**Comment by snail-z** [comment]
确实有这个问题，我已经做了修改。 
不过叠加弹出窗口应该是不合理的，另外这样操作相当于创建了两个不同的对象赋给了self.sl_popupController ，所以前一个已经delloc了 ，但是视图没有消失（这是个bug）。如果非要同时叠加多个，应该创建多个不同的全局变量来保存每个对象。
