### ISSUE TITLE
pod的问题

### ISSUE THREAD

**Issue by loveJuly** [snail-z/zhPopupController#8]
根据前面的issues解决了在pod上搜索不到的问题，pod到项目里面之后，却一直引用不了，命令行提示：Unable to read the license file `/Users/XXX/XXX/Pods/SnailPopupController/LICENCE` for the spec `SnailPopupController (2.0.6)`

**Comment by rydensun** [comment]
+1

**Comment by loveJuly** [comment]
后来我手动导入了...
